version: '3.8'

services:
  jupyterlab:
    container_name: jupyter-cuda
    user: root
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_TOKEN=token
      - NB_USER=jupyternb
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
    volumes:
      - ./notebooks:/home/jupyternb
    working_dir: /home/jupyternb
    ports:
      - '8888:8888'
    command: >
      bash -c "apt-get update &&
               apt-get install -y python3 python3-pip &&
               pip3 install --upgrade pip &&
               pip3 install jupyterlab numpy numba &&
               jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='token'"

