version: '3.8'

services:
  numba-cuda-app:
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    container_name: numba_cuda_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: >
      bash -c "apt-get update &&
               apt-get install -y python3 python3-pip &&
               pip3 install numpy numba &&
               tail -f /dev/null"
    volumes:
      - ./:/workspace
    working_dir: /workspace